export default {
    products: [
        {
            _id: '1',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-1.png',
            price: 57,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Nike Full-Zip Polo Shirts',
            category: 'Shirts',
            image: '/images/product-2.png',
            price: 65,
            brand: 'Wyte',
            rating: 5,
            numReviews: 51,
            countInStock: 10,
        },
        {
            _id: '3',
            name: 'FRound neck ',
            category: 'Shirts',
            image: '/images/product-3.png',
            price: 50,
            brand: 'Lauren',
            rating: 5.5,
            numReviews: 20,
            countInStock:39,
        },
        {
            _id: '4',
            name: 'Suity Shirts',
            category: 'Shirts',
            image: '/images/product-4.png',
            price: 70,
            brand: 'Moweeen',
            rating: 3.5,
            numReviews: 9,
            countInStock: 10,
        },
        {
            _id: '5',
            name: 'Miky Mouse T-shirt',
            category: 'Shirts',
            image: '/images/product-5.png',
            price: 55,
            brand: 'Micky',
            rating: 4.5,
            numReviews: 8,
            countInStock: 16.
        },
        {
            _id: '5',
            name: 'Blue Movie Shirts',
            category: 'Shirts',
            image: '/images/product-6.png',
            price: 60,
            brand: 'New Design Move',
            rating: 3.5,
            numReviews: 12,
            countInStock: 20.
        },
    ],
};